fix: add missing import generate_qr_data at module level
ERROR: name 'generate_qr_data' is not defined

SOLUTION: Added import at top of file
from utils.qr_security import generate_qr_data

This will fix QR code generation!