fix: remove @app.route decorator from validate_transaction
ERROR FIXED:
NameError: name 'app' is not defined

CAUSE:
- patch script added @app.route() in controller
- Controllers shouldn't have route decorators
- Routes are defined in transaction_route.py

SOLUTION:
- Removed @app.route('/transactions/validate')
- Function validate_transaction() now clean
- Route registered properly via transaction_route.py

App will now start correctly!